# Change these first
owner: Revival-Dev # Your GitHub organization or username, where this repository lives
repo: severus # The name of this repository

sites:
  - name: Portal
    url: https://www.revivaltv.id
  - name: RevivalPedia
    url: https://revivalpedia.com
  - name: RevivalPedia API
    url: https://api.revivalpedia.com
  - name: Livescore
    url: https://livescore.revivaltv.id/api/tournaments
  - name: Beta RevivalTV
    url: https://beta.revivaltv.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: night
  baseUrl: /severus
  logoUrl: https://revivaltv.s3.ap-southeast-1.amazonaws.com/rvl-logo.png
  name: Severus
  introTitle: "**Severus** RevivalTV's servers status monitoring."
  introMessage: "Powered by **GitHub** & **Upptime** https://upptime.js.org."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
